services:
  - type: web
    name: telegram-bot-boletas
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
    plan: free
